### PR TITLE
HTML2PATS

### PR DESCRIPTION
**Pull request by ashalkhakov**
This is a tool for preprocessing HTML. Please see the README file.

The rest is, well, some left-over code (could not find any way to remove it safely from this PR). Sadly, I don't use branches as often as I should.

### CODE REVIEW

**Comment by githwxi** [comment]
First, thanks for contributing.

I took a look at the code.

Could you put your name in the files inside the html2pats project?

**Comment by ashalkhakov** [comment]
2016-01-13 13:02 GMT+06:00 Hongwei Xi <notifications@github.com>:

> First, thanks for contributing.
>
> I took a look at the code.
>
> Could you put your name in the files inside the html2pats project?
>
Sure, will do when I'm back at my laptop. Probably will have to put the
license as well.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/githwxi/ATS-Postiats-contrib/pull/39#issuecomment-171197356>
> .
>



-- 
Cheers,
Artyom Shalkhakov

**Comment by ashalkhakov** [comment]
I've added some comments. What do you think?

**Comment by githwxi** [comment]
Could you push the changes into GitHub?

**Comment by githwxi** [comment]
I added the html2pats prject manually at:

$(ATSCONTRIB)/projects/ashalkhakov/html2pats

Thanks for contributing!

**Pull request closed without merging**
